# Bash
alias l='ls -ahl'
alias v='vimr'
alias vd='vimr --cwd'

# Git
alias g='git status -sb'
alias ga='git add --all'
alias gb='git branch'
alias gca='git commit --amend'
alias gcm='git commit -m'
alias gcv='git commit --no-verify'
alias gd='git diff --color-words'
alias gdc='git diff --cached -w'
alias gdv='git diff'
alias gdw='git diff --no-ext-diff --word-diff'
alias gf='git fetch'
alias gh='git hist'
alias gl='git log --oneline --decorate'
alias gp='git pull'
alias gpr='git pull --rebase'
alias gpp='git pull --rebase && git push'
alias gra='git rebase --abort'
alias grc='git rebase --continue'
alias gri='git rebase -i'
alias grs='git rebase --skip'
alias gs='git stash'
alias gsl='git stash list'
alias gsp='git stash pop'
alias gss='git stash save'
alias gt='git tag'
